name: CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  CI:
    if: ${{ github.repository == 'googleapis/ruby-style' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "3.2"
          - os: ubuntu-latest
            ruby: "3.3"
          - os: ubuntu-latest
            ruby: "3.4"
          - os: ubuntu-latest
            ruby: "4.0"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install tools
      shell: bash
      run: "bundle install && gem install --no-document toys"
    - name: Test
      shell: bash
      run: toys rubocop < /dev/null
